apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openmina.fullname" . }}
  labels:
    {{- include "openmina.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "openmina.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openmina.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openmina.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args:
          - "node"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{ include "openmina.readinessProbe" . | indent 10 }}
          {{ include "openmina.livenessProbe" . | indent 10 }}
          env:
          - name: "CHAIN_ID"
            value: "{{ .Values.chainId }}"
          - name: "VERBOSITY"
            value: "debug"
          {{- if .Values.snarker -}}
          - name: "PUBLIC_KEY"
            value: "{{ .Values.snarker.PublicKey }}"
          - name: "SNARKER_FEE"
            value: "{{ .Values.snarker.fee }}"
          - name: "MINA_EXE_PATH"
            value: "/usr/local/bin/snark-worker"
          {{- end -}}
          {{- if .Values.peers }}
          - name: "PEERS"
            value: "{{ .Values.peers | join " " }}"
          {{- end }}
          {{- if .Values.secretKey }}
          - name: "OPENMINA_P2P_SEC_KEY"
            value: "{{ .Values.secretKey }}"
          {{- end}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
