#!/bin/bash

# Generate .env.docker file with git information for Docker builds
# This script must be run from the project root before building the Docker image

set -e

# Navigate to project root (two levels up from frontend/docker/)
cd "$(dirname "$0")/../.."

# Extract git information
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
GIT_COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')
GIT_COMMIT_AUTHOR_NAME=$(git log -1 --pretty=format:'%an')
GIT_COMMIT_COUNT=$(git rev-list --count HEAD)
GIT_COMMIT_DATE=$(git log -1 --pretty=format:'%cd' --date=short)
GIT_COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')
GIT_COMMIT_TIMESTAMP=$(git log -1 --pretty=format:'%cI')
GIT_DESCRIBE=$(git describe --tags --always --dirty 2>/dev/null || echo "v0.0.0-$(git rev-parse --short HEAD)")
GIT_SHA=$(git rev-parse HEAD)

# Extract build information
BUILD_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
RUSTC_VERSION=$(rustc --version 2>/dev/null || echo "unknown")
RUSTC_CHANNEL=$(echo "$RUSTC_VERSION" | grep -o '\(stable\|beta\|nightly\)' || echo "stable")
RUSTC_SEMVER=$(echo "$RUSTC_VERSION" | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+' || echo "0.0.0")
TARGET_TRIPLE=$(rustc --version --verbose 2>/dev/null | grep "host:" | cut -d' ' -f2 || echo "unknown")

# Extract Cargo information from current build context
CARGO_FEATURES="${CARGO_FEATURES:-default}"
CARGO_OPT_LEVEL="${CARGO_OPT_LEVEL:-0}"
CARGO_TARGET_TRIPLE="${CARGO_BUILD_TARGET:-$TARGET_TRIPLE}"
CARGO_DEBUG="${CARGO_DEBUG:-true}"

# Write to .env.docker using grouped commands
{
    echo "# VERGEN environment variables for Docker builds"
    echo "# Generated automatically from git and build information"
    echo "# Do not edit this file manually - run ./generate-docker-env.sh instead"
    echo ""
    echo "# Git information"
    echo "VERGEN_GIT_BRANCH=$GIT_BRANCH"
    echo "VERGEN_GIT_COMMIT_AUTHOR_EMAIL=$GIT_COMMIT_AUTHOR_EMAIL"
    echo "VERGEN_GIT_COMMIT_AUTHOR_NAME=$GIT_COMMIT_AUTHOR_NAME"
    echo "VERGEN_GIT_COMMIT_COUNT=$GIT_COMMIT_COUNT"
    echo "VERGEN_GIT_COMMIT_DATE=$GIT_COMMIT_DATE"
    echo "VERGEN_GIT_COMMIT_MESSAGE=$GIT_COMMIT_MESSAGE"
    echo "VERGEN_GIT_COMMIT_TIMESTAMP=$GIT_COMMIT_TIMESTAMP"
    echo "VERGEN_GIT_DESCRIBE=$GIT_DESCRIBE"
    echo "VERGEN_GIT_SHA=$GIT_SHA"
    echo ""
    echo "# Build information"
    echo "VERGEN_BUILD_TIMESTAMP=$BUILD_TIMESTAMP"
    echo ""
    echo "# Cargo information"
    echo "VERGEN_CARGO_FEATURES=$CARGO_FEATURES"
    echo "VERGEN_CARGO_OPT_LEVEL=$CARGO_OPT_LEVEL"
    echo "VERGEN_CARGO_TARGET_TRIPLE=$CARGO_TARGET_TRIPLE"
    echo "VERGEN_CARGO_DEBUG=$CARGO_DEBUG"
    echo ""
    echo "# Rustc information"
    echo "VERGEN_RUSTC_CHANNEL=$RUSTC_CHANNEL"
    echo "VERGEN_RUSTC_SEMVER=$RUSTC_SEMVER"
    echo "VERGEN_RUSTC_HOST_TRIPLE=$TARGET_TRIPLE"
    echo "VERGEN_RUSTC_COMMIT_DATE=unknown"
    echo "VERGEN_RUSTC_COMMIT_HASH=unknown"
    echo "VERGEN_RUSTC_LLVM_VERSION=unknown"
} > .env.docker

echo "Generated .env.docker with build information:"
echo "- Branch: $GIT_BRANCH"
echo "- Commit: $GIT_SHA"
echo "- Author: $GIT_COMMIT_AUTHOR_NAME <$GIT_COMMIT_AUTHOR_EMAIL>"
echo "- Message: $GIT_COMMIT_MESSAGE"
echo "- Build Time: $BUILD_TIMESTAMP"
echo "- Rust Channel: $RUSTC_CHANNEL"
echo "- Rust Version: $RUSTC_SEMVER"
echo "- Target: $CARGO_TARGET_TRIPLE"
