//! # Circuit Constraint Extraction
//!
//! This module handles circuit constraint extraction for the Mina Rust node.
//! Circuit constraints are sourced from the
//! [circuit-blobs](https://github.com/o1-labs/circuit-blobs) repository, which
//! contains pre-compiled circuit data generated by the OCaml implementation.
//!
//! ## Overview
//!
//! The Mina Rust node automatically handles downloading and caching circuit
//! files, making the process transparent to users. When you run the node or
//! generate proofs, the system will automatically fetch the required circuit
//! data if it's not already available locally.
//!
//! ## Circuit Data Files
//!
//! The circuit-blobs repository contains three types of files for each circuit:
//!
//! ### Gates Definition (`*_gates.json`)
//!
//! - JSON files containing the list of gates for each circuit
//! - Define the circuit structure and operations
//! - Used for generating proving and verification keys
//!
//! ### Internal Variables (`*_internal_vars.bin`)
//!
//! - Binary files containing internal variable mappings
//! - Store relationships between field elements and variable indices
//! - Essential for witness generation
//!
//! ### Row Reversal Data (`*_rows_rev.bin`)
//!
//! - Binary files containing constraint system data
//! - Used for efficient constraint evaluation
//! - Required for proof generation
//!
//! ## Extraction Process
//!
//! The Mina Rust node automatically handles circuit constraint extraction
//! through this module's [`fetch_blocking`] function.
//!
//! ### Local Resolution
//!
//! The system searches for circuit files in these locations (in order):
//!
//! 1. **Environment Variable**: `MINA_CIRCUIT_BLOBS_BASE_DIR`
//! 2. **Cargo Manifest Directory**: Current project directory
//! 3. **Home Directory**: `~/.mina/circuit-blobs/`
//! 4. **System Directory**: `/usr/local/lib/mina/circuit-blobs`
//!
//! ### Remote Fetching
//!
//! If files are not found locally, the system automatically downloads them from:
//!
//! ```text
//! https://github.com/o1-labs/circuit-blobs/releases/download/<filename>
//! ```
//!
//! Downloaded files are cached locally for future use.
//!
//! ## Web Environment
//!
//! For web deployments, circuit files are served statically:
//!
//! - **Frontend Path**: `/assets/webnode/circuit-blobs/<version>/`
//! - **Version**: Specified by `CIRCUITS_VERSION` environment variable
//!
//! ## How It Works for Users
//!
//! ### First Run Experience
//!
//! When you first run the Mina Rust node or generate proofs:
//!
//! 1. **Automatic Detection**: The system checks for required circuit files
//! 2. **Local Search**: Searches in these locations (in order):
//!    - `$MINA_CIRCUIT_BLOBS_BASE_DIR` (if set)
//!    - Current project directory
//!    - `~/.mina/circuit-blobs/`
//!    - `/usr/local/lib/mina/circuit-blobs`
//! 3. **Automatic Download**: If files aren't found locally, downloads from GitHub
//! 4. **Local Caching**: Saves downloaded files to `~/.mina/circuit-blobs/`
//! 5. **Ready to Use**: Circuit data is loaded and ready for proof generation
//!
//! ### Subsequent Runs
//!
//! - Uses cached files from `~/.mina/circuit-blobs/`
//! - No network requests needed
//! - Fast startup times
//!
//! ## Development Guidelines
//!
//! ### Adding New Circuit Types
//!
//! 1. Generate circuit data using OCaml implementation
//! 2. Add files to circuit-blobs repository
//! 3. Update circuit configuration in `mina_core::network`
//! 4. Add prover creation logic in [`crate::proofs::provers`]
//!
//! ### Local Development
//!
//! Set `MINA_CIRCUIT_BLOBS_BASE_DIR` environment variable to point to your
//! local circuit-blobs repository clone:
//!
//! ```bash
//! export MINA_CIRCUIT_BLOBS_BASE_DIR=/path/to/your/circuit-blobs
//! ```
//!
//! ## Related Modules
//!
//! - [`crate::proofs::provers`]: Prover creation using circuit data
//! - [`crate::proofs::constants`]: Circuit type definitions

use std::path::Path;

#[cfg(not(target_family = "wasm"))]
pub fn home_base_dir() -> Option<std::path::PathBuf> {
    let mut path = std::path::PathBuf::from(std::env::var("HOME").ok()?);
    path.push(".mina/circuit-blobs");
    Some(path)
}

fn git_release_url(filename: &impl AsRef<Path>) -> String {
    const RELEASES_PATH: &str = "https://github.com/o1-labs/circuit-blobs/releases/download";
    let filename_str = filename.as_ref().to_str().unwrap();

    format!("{RELEASES_PATH}/{filename_str}")
}

#[cfg(not(target_family = "wasm"))]
pub fn fetch_blocking(filename: &impl AsRef<Path>) -> std::io::Result<Vec<u8>> {
    use std::path::PathBuf;

    fn try_base_dir<P: Into<PathBuf>>(base_dir: P, filename: &impl AsRef<Path>) -> Option<PathBuf> {
        let mut path = base_dir.into();
        path.push(filename);
        path.exists().then_some(path)
    }

    fn to_io_err(err: impl std::fmt::Display) -> std::io::Error {
        std::io::Error::other(format!(
            "failed to find circuit-blobs locally and to fetch the from github! error: {err}"
        ))
    }

    let home_base_dir = home_base_dir();
    let found = None
        .or_else(|| try_base_dir(std::env::var("MINA_CIRCUIT_BLOBS_BASE_DIR").ok()?, filename))
        .or_else(|| try_base_dir(env!("CARGO_MANIFEST_DIR").to_string(), filename))
        .or_else(|| try_base_dir(home_base_dir.clone()?, filename))
        .or_else(|| try_base_dir("/usr/local/lib/mina/circuit-blobs", filename));

    if let Some(path) = found {
        return std::fs::read(path);
    }

    mina_core::info!(
        mina_core::log::system_time();
        kind = "ledger proofs",
        message = "circuit-blobs not found locally, so fetching it...",
        filename = filename.as_ref().to_str().unwrap(),
    );

    let base_dir = home_base_dir.expect("$HOME env not set!");

    let bytes = reqwest::blocking::get(git_release_url(filename))
        .map_err(to_io_err)?
        .bytes()
        .map_err(to_io_err)?
        .to_vec();

    // cache it to home dir.
    let cache_path = base_dir.join(filename);
    mina_core::info!(
        mina_core::log::system_time();
        kind = "ledger proofs",
        message = "caching circuit-blobs",
        path = cache_path.to_str().unwrap(),
    );
    let _ = std::fs::create_dir_all(cache_path.parent().unwrap());
    let _ = std::fs::write(cache_path, &bytes);

    Ok(bytes)
}

#[cfg(target_family = "wasm")]
pub async fn fetch(filename: &impl AsRef<Path>) -> std::io::Result<Vec<u8>> {
    let prefix =
        option_env!("CIRCUIT_BLOBS_HTTP_PREFIX").unwrap_or("/assets/webnode/circuit-blobs");
    let url = format!("{prefix}/{}", filename.as_ref().to_str().unwrap());
    mina_core::http::get_bytes(&url).await
}

#[cfg(target_family = "wasm")]
pub fn fetch_blocking(filename: &impl AsRef<Path>) -> std::io::Result<Vec<u8>> {
    let prefix =
        option_env!("CIRCUIT_BLOBS_HTTP_PREFIX").unwrap_or("/assets/webnode/circuit-blobs");
    let url = format!("{prefix}/{}", filename.as_ref().to_str().unwrap());
    mina_core::http::get_bytes_blocking(&url)
}
