[package]
name = "transaction_fuzzer"
version = "0.13.0"
edition = "2021"


[dependencies]
ark-serialize = "0.4.2"
poseidon = { workspace = true }
mina-hasher = { workspace = true }
mina-signer = { workspace = true }
mina-curves = { workspace = true }
mina-p2p-messages = { workspace = true }
ark-ff = { workspace = true }
openmina-core = { path = "../../core" }
ledger = { path = "../../ledger", package = "mina-tree", features = ["fuzzing"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
flate2 = "1.0.24"
md5 = "0.7.0"
btreemultimap = "0.1.1"
bitvec = "1.0.1"
object = "0.36.4"
rsprocmaps = "0.3.2"
leb128 = "0.2.1"
rand = { version = "0.8.5", features = ["small_rng"] }
ring_buffer = "2.0.2"
ark-ec = { version = "0.3.0", features = [ "std" ] }
#ark-ff = { git = "https://github.com/openmina/algebra", branch = "openmina", features = [ "parallel", "asm", "std" ] }
#ark-ec = { git = "https://github.com/openmina/algebra", branch = "openmina", features = [ "std" ] }
once_cell = "1.18.0"
text-diff = "0.4.0"
num-bigint = "0.4.0"
tuple-map = "0.4.0"
itertools = "0.11.0"
#binprot = "0.1.7"
binprot = { git = "https://github.com/openmina/binprot-rs", rev = "400b52c" }
binprot_derive = { git = "https://github.com/openmina/binprot-rs", rev = "400b52c" }
clap = "4.5.20"


[profile.release]
opt-level = 3
debug = 2
debug-assertions = true
overflow-checks = true
lto = true
panic = "abort"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(unstable)'] }

[features]
nightly = []