kind: pipeline
type: docker
name: test-bootstrap

trigger:
  branch:
  - master
  - feat/standalone_snark_worker

environment:
  CHAIN_ID: 667b328bfc09ced12191d099f234575b006b6b193f5441a6fa744feacd9744db

  REPLAYER_ID: 12D3KooWETkiRaHCdztkbmrWQTET9HMWimQPx5sH5pLSRZNxRsjw

  OPENMINA1_SK: 5KJKg7yAbYAQcNGWcKFf2C4ruJxwrHoQvsksU16yPzFzXHMsbMc
  OPENMINA1_ID: 2axsdDAiiZee7hUsRPMtuyHt94UMrvJmMQDhDjKhdRhgqkMdy8e
  OPENMINA1_SNARKER_KEY: B62qqYvLLtTMQtHxRfuzZK21AJrqFE8Zq9Cyk3wtjegiTRn5soNQA9A

  OPENMINA2_SK: 5JgkZGzHPC2SmQqRGxwbFjZzFMLvab5tPwkiN29HX9Vjc9rtwV4
  OPENMINA2_ID: 2bpACUcRh2u7WJ3zSBRWZZvQMTMofYr9SGQgcP2YKzwwDKanNAy
  OPENMINA2_SNARKER_KEY: B62qrV28zSmLjxMZP1jKRSEFsajPGdFRukbvnXzRKyDmUBNVvCH7w9o

  OPENMINA3_SK: 5KWkmiairnLJjtvqEatpb4grLEG8oZjFp7ye4ehphjXRGrgsuH8
  OPENMINA3_ID: 2aQA3swTKVf16YgLXZS7TizU7ASgZ8LidEgyHhChpDinrvM9NMi
  OPENMINA3_SNARKER_KEY: B62qkgVSEnzTabaFJzZcG1pgXorRLJREJFvchGya6UGoKTmFx5AWAK6

steps:

  - name: submodules
    image: alpine/git
    environment:
      GITHUB_AUTH_TOKEN:
        from_secret: github_auth_token
    commands:
      - git config --global url."https://$${GITHUB_AUTH_TOKEN}:@github.com/".insteadOf "https://github.com/"
      - git config --global --add safe.directory /drone/src
      - git config --global --add safe.directory /drone/src/ledger
      - git config --global --add safe.directory /drone/src/mina-p2p-messages-rs
      - git config --global --add safe.directory /drone/src/deps/algebra
      - git config --global --add safe.directory /drone/src/deps/proof-systems
      - git config --global --add safe.directory /drone/src/deps/redux-rs
      - git submodule update --init --recursive
      - rm ~/.gitconfig

  - name: prepare-snark-worker
    image: openmina/mina-snark-worker-prover:0.0.7
    commands:
      - cp /usr/local/bin/mina cli/bin/mina.exe

  - name: build
    image: rust:1.71-buster
    commands:
      - apt-get update && apt-get install -y libssl-dev libjemalloc-dev
      - rustup update nightly-2023-06-01 && rustup default nightly-2023-06-01
      - rustup component add rustfmt
      - cargo test --release -p cli
      - cargo build --release -p cli --bin openmina

  - name: replayer
    image: vladsimplestakingcom/bootstrap-rr:latest
    detach: true
    commands:
      - RUST_LOG=info openmina-bootstrap-sandbox replay 7548

  - name: openmina1
    image: openmina/mina-snark-worker-prover:0.0.7
    detach: true
    commands:
      - target/release/openmina snarker -p 10000 --chain-id $CHAIN_ID -k $OPENMINA1_SNARKER_KEY -s $OPENMINA1_SK
          --peers /dns4/replayer/tcp/8302/p2p/$REPLAYER_ID /$OPENMINA2_ID/http/openmina2/10000 /$OPENMINA3_ID/http/openmina3/10000
          -e cli/bin/mina > /dev/null

  - name: openmina2
    image: openmina/mina-snark-worker-prover:0.0.7
    detach: true
    commands:
      - target/release/openmina snarker -p 10000 --chain-id $CHAIN_ID -k $OPENMINA2_SNARKER_KEY -s $OPENMINA2_SK
          --peers /dns4/replayer/tcp/8302/p2p/$REPLAYER_ID /$OPENMINA1_ID/http/openmina1/10000 /$OPENMINA3_ID/http/openmina3/10000
          -e cli/bin/mina > /dev/null

  - name: openmina3
    image: openmina/mina-snark-worker-prover:0.0.7
    detach: true
    commands:
      - target/release/openmina snarker -p 10000 --chain-id $CHAIN_ID -k $OPENMINA3_SNARKER_KEY -s $OPENMINA3_SK
          --peers /dns4/replayer/tcp/8302/p2p/$REPLAYER_ID /$OPENMINA1_ID/http/openmina1/10000 /$OPENMINA2_ID/http/openmina2/10000
          -e cli/bin/mina > /dev/null

  - name: test-bootstrap
    image: vladsimplestakingcom/bootstrap-rr:latest
    commands:
      - sleep 300
      - RUST_LOG=debug timeout 3600s openmina-bootstrap-sandbox test 7548 http://openmina1:10000/stats/sync


  - name: test-snark-work
    image: alpine
    commands:
      - apk add curl jq
      - |
        c() {
           n=$$1
           path=$$2
           shift 2
           curl -s http://openmina$$n:10000/$$path "$$@"
        }
      - |
        assert() {
          eval $2 || {
            echo "[failed] $1: '$2'"
            exit 1
          }
        }
      - |
        TOTAL_WORK_TODO=$$(c 1 snark-pool/jobs | jq 'length')
        echo "TOTAL_WORK_TODO=$TOTAL_WORK_TODO"
        LOCAL_WORK=0
        for t in $(seq 10); do
          WORKERS=$$(c 1 snarker/workers | jq '[.[] | select(.status.kind != "None")] | length')
          assert 'active workers > 0' '[ $$WORKERS -gt 0 ]'

          COMMITMENTS_IN_PROGRESS=$$(c 1 snark-pool/jobs | jq "[.[] | select(.snark == null and .commitment.snarker == \"$OPENMINA1_SNARKER_KEY\")] | length")
          assert 'local commitments in progress fewer than local workers' '[ $$COMMITMENTS_IN_PROGRESS -le $$WORKERS ]'

          LW=$$(c 1 snark-pool/jobs | jq "[.[] | select(.snark.snarker == \"$OPENMINA1_SNARKER_KEY\")] | length")
          assert 'local snarks number do not decrease' '[ $$LOCAL_WORK -le $$LW ]'
          LOCAL_WORK=$$LW


          sleep 30
        done

        c 1 snark-pool/jobs > jobs.json

        assert 'local work exists' '[ $$LOCAL_WORK -gt 0 ]'

        TOTAL_WORK=$$(jq '[.[] | select(.snark != null)] | length' jobs.json)
        LOCAL_WORK=$$(jq "[.[] | select(.snark != null and .snark.snarker == \"$OPENMINA1_SNARKER_KEY\")] | length" jobs.json)
        NON_LOCAL_WORK=$$(jq "[.[] | select(.snark != null and .snark.snarker != \"$OPENMINA1_SNARKER_KEY\")] | length" jobs.json)
        echo "TOTAL_WORK=$$TOTAL_WORK"
        echo "LOCAL_WORK=$$LOCAL_WORK"
        echo "NON_LOCAL_WORK=$$NON_LOCAL_WORK"
        #assert 'non-local work exists' '[ $$NON_LOCAL_WORK -gt 0 ]'

        TOTAL_COMMITMENTS=$$(jq "[.[] | select(.commitment != null)] | length" jobs.json)
        NON_LOCAL_COMMITMENTS=$$(jq "[.[] | select(.commitment != null and .commitment.commitment.snarker != \"$OPENMINA1_SNARKER_KEY\")] | length" jobs.json)
        echo "TOTAL_COMMITMENTS=$$TOTAL_COMMITMENTS"
        echo "NON_LOCAL_COMMITMENTS=$$NON_LOCAL_COMMITMENTS"
        assert 'non-local commintment exists' '[ $$NON_LOCAL_COMMITMENTS -gt 0 ]'
