kind: pipeline
type: docker
name: test-bootstrap

trigger:
  branch:
  - master
  - feat/standalone_snark_worker

steps:

  - name: submodules
    image: alpine/git
    environment:
      GITHUB_AUTH_TOKEN:
        from_secret: github_auth_token
    commands:
      - git config --global url."https://$${GITHUB_AUTH_TOKEN}:@github.com/".insteadOf "https://github.com/"
      - git config --global --add safe.directory /drone/src
      - git config --global --add safe.directory /drone/src/ledger
      - git config --global --add safe.directory /drone/src/mina-p2p-messages-rs
      - git config --global --add safe.directory /drone/src/deps/algebra
      - git config --global --add safe.directory /drone/src/deps/proof-systems
      - git config --global --add safe.directory /drone/src/deps/redux-rs
      - git submodule update --init --recursive
      - rm ~/.gitconfig

  - name: build
    image: rust:1.71-buster
    commands:
      - rustup update nightly-2023-06-01 && rustup default nightly-2023-06-01
      - rustup component add rustfmt
      - cargo build --release -p cli --bin openmina --tests

  - name: replayer
    image: vladsimplestakingcom/bootstrap-rr:latest
    detach: true
    commands:
      - RUST_LOG=info openmina-bootstrap-sandbox replay 7548

  - name: openmina
    image: debian:buster
    detach: true
    commands:
      - target/release/openmina snarker -p 10000 --chain-id 667b328bfc09ced12191d099f234575b006b6b193f5441a6fa744feacd9744db -k B62qqYvLLtTMQtHxRfuzZK21AJrqFE8Zq9Cyk3wtjegiTRn5soNQA9A --peer /dns4/replayer/tcp/8302/p2p/12D3KooWETkiRaHCdztkbmrWQTET9HMWimQPx5sH5pLSRZNxRsjw

  - name: test-bootstrap
    image: vladsimplestakingcom/bootstrap-rr:latest
    commands:
      - sleep 300
      - RUST_LOG=debug timeout 3600s openmina-bootstrap-sandbox test 7548 http://openmina:10000/stats/sync
