kind: pipeline
type: docker
name: test-bootstrap

trigger:
  branch:
  - master
  - feat/standalone_snark_worker
  - feat/graphql

steps:
  - name: empty
    image: vladsimplestakingcom/bootstrap-rr:graphql
    pull: always
    detach: true
    environment:
      # 12D3KooWBk4vJzxBZcwDXEae91mPLxJZks2pUCpDJP1zmCjx95ai
      OPENMINA_P2P_SEC_KEY: 5KRTpP4DczohhCkYVSZCHNzEF2t8Lig1EwbUPkR7TT2b4gMYYer
      RUST_LOG: info
    commands:
      - openmina-bootstrap-sandbox --listen='/ip6/::/tcp/8302' --listen='/ip4/0.0.0.0/tcp/8302' empty

  - name: generate-mina-key
    image: minaprotocol/mina-daemon:2.0.0rampup3-bfd1009-buster-berkeley
    volumes:
      - name: mina-key
        path: /key
    environment:
      MINA_LIBP2P_PASS: _
    commands:
      - chmod 700 /key
      - mina libp2p generate-keypair --privkey-path /key/key

  - name: replay
    image: vladsimplestakingcom/bootstrap-rr:graphql
    pull: always
    detach: true
    environment:
      # 12D3KooWETkiRaHCdztkbmrWQTET9HMWimQPx5sH5pLSRZNxRsjw
      OPENMINA_P2P_SEC_KEY: 5JDRBqXfHm4Xne1QKUJyg9FKRfwN6gtduZb7nVYHg2F1BmwPynT
      RUST_LOG: info
    commands:
      - openmina-bootstrap-sandbox --path='/tmp/mina-record' --chain-id='667b328bfc09ced12191d099f234575b006b6b193f5441a6fa744feacd9744db' --listen='/ip6/::/tcp/8302' --listen='/ip4/0.0.0.0/tcp/8302' replay 7548

  - name: bootstrap-replyer-to-openmina
    image: rust:1.71-buster
    detach: true
    volumes:
      - name: mina-key
        path: /key
    environment:
      # 12D3KooWD8jSyPFXNdAcMBHyHjRBcK1AW9t3xvnpfCFSRKMweVKi
      # 2ajh5CpZCHdv7tmMrotVnLjQXuhcuCzqKosdDmvN3tNTScw2fsd
      OPENMINA_P2P_SEC_KEY: 5JrKG84DTn8CSF58zyUvHt9yg6zp9wL9J3jjLKWLawnz3BJ12Ye
      GITHUB_AUTH_TOKEN:
        from_secret: github_auth_token
    commands:
      - rustup update nightly-2023-06-01 && rustup default nightly-2023-06-01
      - rustup component add rustfmt
      - git config --global url."https://$${GITHUB_AUTH_TOKEN}:@github.com/".insteadOf "https://github.com/"
      - git config --global --add safe.directory /drone/src
      - git config --global --add safe.directory /drone/src/ledger
      - git config --global --add safe.directory /drone/src/mina-p2p-messages-rs
      - git config --global --add safe.directory /drone/src/deps/algebra
      - git config --global --add safe.directory /drone/src/deps/proof-systems
      - git config --global --add safe.directory /drone/src/deps/redux-rs
      - git submodule init && git submodule update --recursive
      - cargo run --release -p cli snarker -p 10000 --chain-id 667b328bfc09ced12191d099f234575b006b6b193f5441a6fa744feacd9744db -k B62qqYvLLtTMQtHxRfuzZK21AJrqFE8Zq9Cyk3wtjegiTRn5soNQA9A --peer /dns4/replay/tcp/8302/p2p/12D3KooWETkiRaHCdztkbmrWQTET9HMWimQPx5sH5pLSRZNxRsjw --peer /dns4/bootstrap-openmina-to-mina/tcp/8302/p2p/$(cat /key/key.peerid)
      - rm ~/.gitconfig

  - name: test-replyer-to-openmina
    image: vladsimplestakingcom/bootstrap-rr:graphql
    pull: always
    environment:
      RUST_LOG: debug
    commands:
      - sleep 300
      - timeout 3600s openmina-bootstrap-sandbox --path='/tmp/mina-record' test-graphql 7548 http://bootstrap-replyer-to-openmina:10000/graphql

  - name: bootstrap-openmina-to-mina
    image: minaprotocol/mina-daemon:2.0.0rampup3-bfd1009-buster-berkeley
    detach: true
    volumes:
      - name: mina-key
        path: /key
    environment:
      MINA_LIBP2P_PASS: _
    commands:
      - curl https://raw.githubusercontent.com/MinaProtocol/mina/bfd1009/genesis_ledgers/berkeley.json -o /berkeley.json
      - mina daemon --external-port 8302 --config-file /berkeley.json --libp2p-keypair /key/key --peer /dns4/empty/tcp/8302/p2p/12D3KooWBk4vJzxBZcwDXEae91mPLxJZks2pUCpDJP1zmCjx95ai --direct-peer /dns4/bootstrap-replyer-to-openmina/tcp/8302/p2p/12D3KooWD8jSyPFXNdAcMBHyHjRBcK1AW9t3xvnpfCFSRKMweVKi --insecure-rest-server -log-level Debug

  - name: test-openmina-to-mina
    image: vladsimplestakingcom/bootstrap-rr:graphql
    pull: always
    environment:
      RUST_LOG: debug
    commands:
      - sleep 300
      - timeout 3600s openmina-bootstrap-sandbox --path='/tmp/mina-record' test-graphql 7548 http://bootstrap-openmina-to-mina:3085/graphql

  - name: bootstrap-openmina-to-openmina
    image: rust:1.71-buster
    detach: true
    environment:
      # 2bwbtKYyqRrfEHdpVtPLu15fTajcGg5S2JAH31feSAu4VfG2s1c
      OPENMINA_P2P_SEC_KEY: 5JR6qDMQFczLXNWLZQDkuJ316GVzV52xh1JYz6YaAkms8282Vy5
      GITHUB_AUTH_TOKEN:
        from_secret: github_auth_token
    commands:
      - rustup update nightly-2023-06-01 && rustup default nightly-2023-06-01
      - rustup component add rustfmt
      - git config --global url."https://$${GITHUB_AUTH_TOKEN}:@github.com/".insteadOf "https://github.com/"
      - git config --global --add safe.directory /drone/src
      - git config --global --add safe.directory /drone/src/ledger
      - git config --global --add safe.directory /drone/src/mina-p2p-messages-rs
      - git config --global --add safe.directory /drone/src/deps/algebra
      - git config --global --add safe.directory /drone/src/deps/proof-systems
      - git config --global --add safe.directory /drone/src/deps/redux-rs
      - git submodule init && git submodule update --recursive
      - cargo run --release -p cli snarker -p 10000 --chain-id 667b328bfc09ced12191d099f234575b006b6b193f5441a6fa744feacd9744db -k B62qqYvLLtTMQtHxRfuzZK21AJrqFE8Zq9Cyk3wtjegiTRn5soNQA9A --peer /2ajh5CpZCHdv7tmMrotVnLjQXuhcuCzqKosdDmvN3tNTScw2fsd/http/bootstrap-replyer-to-openmina/10000
      - rm ~/.gitconfig

  - name: test-openmina-to-openmina
    image: vladsimplestakingcom/bootstrap-rr:graphql
    pull: always
    environment:
      RUST_LOG: debug
    commands:
      - sleep 300
      - timeout 3600s openmina-bootstrap-sandbox --path='/tmp/mina-record' test-graphql 7548 http://bootstrap-openmina-to-openmina:10000/graphql

volumes:
- name: mina-key
  temp: {}
