FROM node:18 AS BUILD_IMAGE
ARG BUILD_CONFIGURATION=producer
WORKDIR /app
COPY frontend/ .
RUN npm install
RUN node_modules/.bin/ng build --configuration ${BUILD_CONFIGURATION}
RUN npm prune --production
FROM nginx:alpine
RUN pwd
RUN ls -l
COPY --from=BUILD_IMAGE /app/dist/frontend /usr/share/nginx/html
COPY --from=BUILD_IMAGE /app/nginx.conf /etc/nginx/nginx.conf

