FROM node:18 AS BUILD_IMAGE
WORKDIR /app
COPY frontend/dist/ ./dist/
COPY frontend/nginx.conf .
FROM nginx:alpine
RUN pwd
RUN ls -l
COPY --from=BUILD_IMAGE /app/dist/frontend /usr/share/nginx/html
COPY --from=BUILD_IMAGE /app/nginx.conf /etc/nginx/nginx.conf
