[package]
name = "error-sink-service"
version = "0.1.0"
edition = "2021"
description = "A service to collect and store error reports from OpenMina nodes"

[dependencies]
actix-web = "4.3"
log = "0.4"
env_logger = "0.11"
chrono = "0.4"
uuid = { version = "1", features = ["v4"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.22"
bs58 = "0.5.0"
