# hadolint ignore=DL3008
FROM vladsimplestakingcom/mina-openmina-builder:focal AS builder

RUN git fetch && git checkout feat/tests-with-debugger

RUN . ~/.cargo/env && cargo +1.84 build --release \
    -p mina-node-testing --bin runner --bin mina-node-testing

FROM vladsimplestakingcom/mina-debugger:2.0.0rampup4-focal

COPY --from=builder /mina/target/release/runner \
    /usr/local/bin/runner
COPY --from=builder /mina/target/release/mina-node-testing \
    /usr/local/bin/mina-node-testing

ENV BPF_ALIAS="3c41383994b87449625df91769dff7b507825c064287d30fada9286f3f1cb15e-0.0.0.0"
