FROM ubuntu:20.04 AS builder

ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone
# hadolint ignore=DL3008
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    apt-get -y install --no-install-recommends git curl gcc libssl-dev \
        pkg-config && \
    rm -rf /var/lib/apt/lists/*

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | \
    sh -s -- -y

RUN source ~/.cargo/env && rustup update 1.84

RUN git clone https://github.com/openmina/openmina

WORKDIR /openmina
