[package]
name = "mina-p2p-messages"
version = "0.6.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.142", features = ["derive"] }
serde_json = { version = "1.0.83" }
hex = "0.4.3"
binprot = { version = "0.1.7" }
binprot_derive = { version = "0.1.7" }
thiserror = "1.0.32"
derive_more = "0.99.17"
bs58 = {version = "0.4", features = ["check"]}
sha2 = { version = "0.10.2", optional = true }

mina-hasher = { git = "https://github.com/o1-labs/proof-systems", optional = true }
mina-curves = { git = "https://github.com/o1-labs/proof-systems", optional = true }
o1-utils = { git = "https://github.com/o1-labs/proof-systems", optional = true }

[target.'cfg(fuzzing)'.dev-dependencies]
fuzzcheck = "0.12.1"

[dev-dependencies]
gloo-utils = "0.1.5"
wasm-bindgen = "0.2.83"
anyhow = "1.0.65"

[features]
hashing = ["mina-hasher", "mina-curves", "o1-utils", "sha2"]

[target.wasm32-unknown-unknown.dev-dependencies]
web-sys = { version = "0.3.60", features = ["console"] }
wasm-bindgen-test = "0.3.33"
wasm-bindgen = "0.2.83"
