[package]
name = "mina-p2p-messages"
version = "0.2.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.142", features = ["derive"] }
serde_json = "1.0.83"
hex = "0.4.3"
binprot = { version = "0.1.7" }
binprot_derive = { version = "0.1.7" }
thiserror = "1.0.32"
derive_more = "0.99.17"

[target.'cfg(fuzzing)'.dev-dependencies]
#[dev-dependencies]
fuzzcheck = "0.12.1"
