[package]
name = "mina-p2p-messages"
version = "0.6.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.142", features = ["derive"] }
serde_json = { version = "1.0.83" }
hex = "0.4.3"
binprot = { git = "https://github.com/name-placeholder/binprot-rs", rev = "ead5ba916725abf8ab212b89985b47c79d1a006a" }
binprot_derive = { git = "https://github.com/name-placeholder/binprot-rs", rev = "ead5ba916725abf8ab212b89985b47c79d1a006a" }
thiserror = "1.0.32"
derive_more = "0.99.17"
bs58 = { version = "0.4", features = ["check"] }
sha2 = { version = "0.10.2", optional = true }

mina-hasher = {git = "https://github.com/o1-labs/proof-systems", rev = "bb0bb776ba6ef39750ac92557947a81c2144b63a", optional = true }
mina-curves = {git = "https://github.com/o1-labs/proof-systems", rev = "bb0bb776ba6ef39750ac92557947a81c2144b63a", optional = true }
mina-signer = {git = "https://github.com/o1-labs/proof-systems", rev = "bb0bb776ba6ef39750ac92557947a81c2144b63a", optional = true }
o1-utils = {git = "https://github.com/o1-labs/proof-systems", rev = "bb0bb776ba6ef39750ac92557947a81c2144b63a", optional = true }
base64 = "0.13.1"

[target.'cfg(fuzzing)'.dev-dependencies]
fuzzcheck = "0.12.1"

[dev-dependencies]
gloo-utils = "0.1.5"
wasm-bindgen = "0.2.83"
anyhow = "1.0.65"
toml = "0.5.9"
clap = { version = "4.0.18", features = ["derive"] }
alloc-test = { git = "https://github.com/name-placeholder/alloc-test.git" }
time = { version = "0.3.17", features = ["formatting"] }


[features]
hashing = ["mina-hasher", "mina-curves", "mina-signer", "o1-utils", "sha2"]

[target.wasm32-unknown-unknown.dev-dependencies]
web-sys = { version = "0.3.60", features = ["console"] }
wasm-bindgen-test = "0.3.33"
wasm-bindgen = "0.2.83"
