# This is a basic workflow to help you get started with Actions

name: Rust Doc

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "compatible" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run cargo doc
        uses: actions-rs/cargo@v1.0.1
        with:
          command: doc
          args: --no-deps

      # Adds redirection to the subdir with crate documentation
      - name: Add subdir redirection
        run: echo "<meta http-equiv=\"refresh\" content=\"0; url=mina_p2p_messages/index.html\">" > target/doc/index.html

      # Uploads build artifacts
      - name: Upload files
        uses: actions/upload-pages-artifact@v1
        with:
          path: target/doc

  deploy:
    needs: build

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
