name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Run memory allocations benchmarks
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --test decode-bench -- decode_alloc --exact --nocapture --ignored -- --load-baseline=tests/decode-bench/alloc

      - name: Run performance benchmarks
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --test decode-bench -- decode_perf --exact --nocapture --ignored -- --load-baseline=tests/decode-bench/perf

  tests-wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Run memory allocations benchmarks
        run: wasm-pack test --firefox --headless . --test decode-bench -- decode_alloc_wasm

      - name: Run memory allocations benchmarks
        run: wasm-pack test --release --firefox --headless . --test decode-bench -- decode_perf_wasm
