name: Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build debug
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --tests

      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --tests

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Run memory allocations benchmarks
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --test decode_alloc -- decode_alloc --exact --nocapture --ignored -- --load-baseline=tests/decode-bench/alloc

      # - name: Run performance benchmarks
      #   uses: actions-rs/cargo@v1
      #   with:
      #     command: test
      #     args: --release --test decode_perf -- decode_perf --exact --nocapture --ignored -- --load-baseline=tests/decode-bench/perf

  tests-wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build debug
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --tests --target=wasm32-unknown-unknown

      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --tests --target=wasm32-unknown-unknown

      - name: Run memory allocations benchmarks
        run: wasm-pack test --firefox --headless . --test decode_alloc -- decode_alloc_wasm

      # - name: Run performance benchmarks
      #   run: wasm-pack test --release --firefox --headless . --test decode_perf -- decode_perf_wasm
