FROM openmina/mina-network-debugger:31f2ca11 as debugger

FROM vladsimplestakingcom/mina-light:2.0.0rampup4-focal

COPY --from=debugger /usr/bin/bpf-recorder /usr/bin/bpf-recorder

RUN apt-get update && apt-get -y install libelf-dev
