FROM debian:buster as builder

RUN apt-get update && \
  apt-get -y install git curl gcc

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

RUN rm /bin/sh && ln -s /bin/bash /bin/sh 

RUN source ~/.cargo/env &&  rustup update nightly-2023-10-01

RUN git clone https://github.com/openmina/openmina

WORKDIR /openmina
