FROM ubuntu:20.04 as builder

ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
  apt-get -y install git curl gcc libssl-dev pkg-config

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN source ~/.cargo/env &&  rustup update 1.75

RUN git clone https://github.com/openmina/openmina

WORKDIR /openmina
