[package]
name = "openmina-fuzzer"
version = "0.8.14"
edition = "2021"
license = "Apache-2.0"

[dependencies]
rand = { version = "0.8", features = [ "small_rng" ] }
rand_distr = "0.4.3"
lazy_static = "1.4.0"
serde = { workspace = true, features = [ "derive" ] }
serde_json = { workspace = true }
