[package]
name = "heartbeats-processor"
version = "0.14.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28", features = ["full", "time"] }
firestore = "0.44"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
chrono = "0.4"
sqlx = { version = "0.8", features = ["runtime-tokio-native-tls", "sqlite", "chrono"] }
dotenv = "0.15"
clap = { version = "4.4", features = ["derive"] }
gcloud-sdk = { version = "0.26.0", default-features = false, features = ["google-firestore-v1"] }
base64 = "0.22"
mina-tree = { path = "../../ledger" }
snark = { path = "../../snark" }

mina-p2p-messages = { workspace = true }
openmina-core = { path = "../../core" }