version: '3.8'

services:
  heartbeats-processor:
    #build: .
    image: openmina/heartbeat-processor:local
    environment:
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT:-staging}
      - WINDOW_RANGE_START=${WINDOW_RANGE_START:-}
      - WINDOW_RANGE_END=${WINDOW_RANGE_END:-}
      #- FIRESTORE_EMULATOR_HOST=${FIRESTORE_EMULATOR_HOST:-}
      - DISABLED_WINDOWS=${DISABLED_WINDOWS:-}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS:-/credentials/service-account.json}
      - DATABASE_PATH=${DATABASE_PATH:-/app/data/store.db}
    volumes:
      - ./data:/app/data
      - ./credentials:/credentials:ro
    command: ["process-loop", "--interval-seconds", "300"]
    restart: unless-stopped

volumes:
  data:
    driver: local
