# Run WebNode with webnode configuration
# This enables WASM node functionality and downloads circuit files
# Note: Replace <TAG> with the tag generated by the build
docker run -p 4200:80 \
  -e MINA_FRONTEND_ENVIRONMENT=webnode \
  o1labs/mina-rust-frontend:<TAG>