[package]
name = "wasm"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.33"
wasm-timer = { git = "https://github.com/fusetim/wasm-timer", branch = "tim-add-missing-methods" }
cfg-if = "1.0.0"
derive_more = "0.99.17"
serde = "1.0.147"
log = { version ="0.4.17", features = ["max_level_trace", "release_max_level_trace"] }
wasm-logger = "0.2.0"
libp2p = { git = "https://github.com/name-placeholder/rust-libp2p", branch="webrtc", features = ["wasm-bindgen", "wasm-ext-webrtc", "serde"] }
redux = { git = "https://github.com/name-placeholder/redux-rs.git", features = ["serde"] }
mina-p2p-messages = { git = "https://github.com/name-placeholder/mina-p2p-messages-rs", branch = "main", features = ["hashing"] }

lib = { path = "../lib" }
