[package]
name = "wasm"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.33"
wasm-timer = { git = "https://github.com/fusetim/wasm-timer", branch = "tim-add-missing-methods" }
redux = { git = "https://github.com/name-placeholder/redux-rs.git", features = ["serde"] }
libp2p = { git = "https://github.com/name-placeholder/rust-libp2p", branch="webrtc", features = ["wasm-bindgen", "wasm-ext-webrtc", "serde"] }

lib = { path = "../lib" }
