[package]
name = "replay_dynamic_effects"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["dylib"]
name = "replay_dynamic_effects"

[dependencies]
mina-node = { workspace = true, features = ["replay"] }
mina-node-invariants = { path = "../../node/invariants" }
mina-node-native = { path = "../../node/native" }
