[package]
name = "mina-node-account"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Account management for Mina nodes, including key generation, encryption, and address handling"

[dependencies]
anyhow = { workspace = true }
bs58 = { workspace = true }
hex = { workspace = true }
lazy_static = { workspace = true }
mina-core = { workspace = true }
mina-hasher = { workspace = true }
mina-p2p-messages = { workspace = true }
mina-signer = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, features = [
  "unbounded_depth",
  "arbitrary_precision",
] }
thiserror = { workspace = true }
utoipa = { workspace = true, optional = true }

[features]
openapi = ["dep:utoipa"]
