[package]
name = "openmina-node-common"
version = "0.16.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
rand = "0.8"
thiserror = "1.0.44"
serde = "1.0.158"
serde_json = "1.0.94"
tracing = "0.1.37"
rayon = "1.5"
jsonpath-rust = "0.5.0"
tokio = { version = "1.26.0", features = ["time", "macros"] }
mina-p2p-messages = { workspace = true }
mina-signer = { workspace = true }
vrf = { workspace = true }
ledger = { workspace = true }
sha3 = "0.10.8"
ark-ff = { workspace = true }
binprot = { git = "https://github.com/openmina/binprot-rs", rev = "400b52c" }
binprot_derive = { git = "https://github.com/openmina/binprot-rs", rev = "400b52c" }
bitflags = "2.8.0"
anyhow = "1"

node = { path = "../../node", features = ["replay"] }
openmina-core = { path = "../../core" }
rsa = "0.9"

[target.'cfg(target_family = "wasm")'.dependencies]
redux = { workspace = true }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
gloo-timers = { version = "0.3", features = ["futures"] }
gloo-utils = "0.2"
tracing-wasm = "0.2"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
redux = { workspace = true, features=["serializable_callbacks"] }
tracing-subscriber = { version = "0.3.17", features = ["json", "env-filter"] }
tracing-appender = "0.2.3"
libp2p-identity = { version = "=0.2.7", features = ["ed25519", "rand", "serde"] }
mio = { version = "1.0.2", features = ["os-poll", "net"] }
reqwest = { version = "0.12.8", features = ["blocking", "json"] }
aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.73.0"
google-cloud-storage = "0.24.0"
google-cloud-auth = "0.17.2"


[features]
p2p-webrtc = ["node/p2p-webrtc"]
p2p-libp2p = ["node/p2p-libp2p"]
