#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum HashParam {
    Account,
    ProtoState,
    ProtoStateBody,
    DeriveTokenId,
    EpochSeed,
    SideloadedVk,
    VrfMessage,
    VrfOutput,
    CodaReceiptUc,
    CoinbaseStack,
    AccountUpdateCons,
    AccountUpdateNode,
    AccountUpdateStackFrame,
    AccountUpdateStackFrameCons,
    ZkappAccount,
    ZkappMemo,
    ZkappUri,
    ZkappEvent,
    ZkappEvents,
    ZkappSeqEvents,
    ZkappActionStateEmptyElt,
    NoInputCoinbaseStack,
    ZkappEventsEmpty,
    ZkappActionsEmpty,
    CodaSignature,
    TestnetZkappBody,
    SignatureMainnet,
    MainnetZkappBody,
    MerkleTree(usize),
    CbMerkleTree(usize),
}

const MERKLE_TREE_STRS: [&str; 36] = [
    "MinaMklTree000",
    "MinaMklTree001",
    "MinaMklTree002",
    "MinaMklTree003",
    "MinaMklTree004",
    "MinaMklTree005",
    "MinaMklTree006",
    "MinaMklTree007",
    "MinaMklTree008",
    "MinaMklTree009",
    "MinaMklTree010",
    "MinaMklTree011",
    "MinaMklTree012",
    "MinaMklTree013",
    "MinaMklTree014",
    "MinaMklTree015",
    "MinaMklTree016",
    "MinaMklTree017",
    "MinaMklTree018",
    "MinaMklTree019",
    "MinaMklTree020",
    "MinaMklTree021",
    "MinaMklTree022",
    "MinaMklTree023",
    "MinaMklTree024",
    "MinaMklTree025",
    "MinaMklTree026",
    "MinaMklTree027",
    "MinaMklTree028",
    "MinaMklTree029",
    "MinaMklTree030",
    "MinaMklTree031",
    "MinaMklTree032",
    "MinaMklTree033",
    "MinaMklTree034",
    "MinaMklTree035",
];

const CB_MERKLE_TREE_STRS: [&str; 6] = [
    "MinaCbMklTree000",
    "MinaCbMklTree001",
    "MinaCbMklTree002",
    "MinaCbMklTree003",
    "MinaCbMklTree004",
    "MinaCbMklTree005",
];

impl From<HashParam> for &'static str {
    fn from(param: HashParam) -> Self {
        match param {
            HashParam::Account => "MinaAccount",
            HashParam::ProtoState => "MinaProtoState",
            HashParam::ProtoStateBody => "MinaProtoStateBody",
            HashParam::DeriveTokenId => "MinaDeriveTokenId",
            HashParam::EpochSeed => "MinaEpochSeed",
            HashParam::SideloadedVk => "MinaSideLoadedVk",
            HashParam::VrfMessage => "MinaVrfMessage",
            HashParam::VrfOutput => "MinaVrfOutput",
            HashParam::CodaReceiptUc => "CodaReceiptUC",
            HashParam::CoinbaseStack => "CoinbaseStack",
            HashParam::AccountUpdateCons => "MinaAcctUpdateCons",
            HashParam::AccountUpdateNode => "MinaAcctUpdateNode",
            HashParam::AccountUpdateStackFrame => "MinaAcctUpdStckFrm",
            HashParam::AccountUpdateStackFrameCons => "MinaActUpStckFrmCons",
            HashParam::ZkappAccount => "MinaZkappAccount",
            HashParam::ZkappMemo => "MinaZkappMemo",
            HashParam::ZkappUri => "MinaZkappUri",
            HashParam::ZkappEvent => "MinaZkappEvent",
            HashParam::ZkappEvents => "MinaZkappEvents",
            HashParam::ZkappSeqEvents => "MinaZkappSeqEvents",
            HashParam::ZkappActionStateEmptyElt => "MinaZkappActionStateEmptyElt",
            HashParam::NoInputCoinbaseStack => "CoinbaseStack",
            HashParam::ZkappEventsEmpty => "MinaZkappEventsEmpty",
            HashParam::ZkappActionsEmpty => "MinaZkappActionsEmpty",
            HashParam::CodaSignature => "CodaSignature",
            HashParam::TestnetZkappBody => "TestnetZkappBody",
            HashParam::SignatureMainnet => "MinaSignatureMainnet",
            HashParam::MainnetZkappBody => "MainnetZkappBody",
            HashParam::MerkleTree(h) => MERKLE_TREE_STRS[h],
            HashParam::CbMerkleTree(h) => CB_MERKLE_TREE_STRS[h],
        }
    }
}
