name: Build macOS Latest

on:
  push:
    branches: [main, develop]
    paths-ignore:
      - 'frontend/**'
  pull_request:
    paths-ignore:
      - 'frontend/**'
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build-reusable.yaml
    with:
      os: macos-latest
      cache-prefix: macos-latest-
      build-wasm: true
      rustflags: "-C link-args=-Wl,-undefined,dynamic_lookup"
