name: Build macOS 14

on:
  schedule:
    # Run every Monday at 6:00 AM UTC
    - cron: '0 6 * * 1'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build-reusable.yaml
    with:
      os: macos-14
      cache-prefix: macos-14-
      build-wasm: true
      rustflags: "-C link-args=-Wl,-undefined,dynamic_lookup"
