name: Frontend CI
on:
  push:
    branches: [ main, develop ]
  pull_request:
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  frontend:
    runs-on: ubuntu-24.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v6

      - id: versions
        uses: ./.github/actions/load-versions

      - name: Frontend build and test
        uses: ./.github/actions/frontend-build
        with:
          node-version: ${{ steps.versions.outputs.node-version }}
          run-prettier-check: 'true'
          run-tests: 'true'
          test-build-commands: 'false'

      - name: Test Docker Build Script
        run: make docker-build-frontend
