name: Frontend macOS 14

on:
  schedule:
    # Run every Monday at 6:00 AM UTC
    - cron: '0 6 * * 1'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  frontend:
    runs-on: macos-14
    steps:
      - name: Git checkout
        uses: actions/checkout@v6

      - id: versions
        uses: ./.github/actions/load-versions

      - name: Frontend build
        uses: ./.github/actions/frontend-build
        with:
          node-version: ${{ steps.versions.outputs.node-version }}
          test-build-commands: 'true'